import { Bug } from "@/types";

export const bugs: Bug[] = [
  {
    id: "b-001",
    title: "Fix theme switch bug",
    description: "Toggle not updating color scheme on Safari",
    priority: "high",
    impact: "medium",
    status: "closed",
    assigneeId: "u-001",
    createdAt: "2025-06-12",
    timeSpent: 1.5,
    updates: [],
    stepsToReproduce:
      "1. Open Safari\n2. Toggle theme switch\n3. Observe no change",
    environment: "Safari 16.4 on macOS",
    startDate: "2025-06-12T10:00:00Z",
    endDate: "2025-06-13T10:00:00Z",
    severity: "high",
  },
  {
    id: "b-002",
    title: "Login button not responsive on mobile",
    description: "Users can't click login on smaller screens.",
    priority: "medium",
    impact: "high",
    status: "open",
    assigneeId: "u-002",
    createdAt: "2025-06-10",
    timeSpent: 0.5,
    updates: [],
    stepsToReproduce:
      "1. Open app on mobile\n2. Try clicking login\n3. Nothing happens",
    environment: "Chrome on Android",
    startDate: "2025-06-10T08:00:00Z",
    endDate: "2025-06-11T08:00:00Z",
    severity: "medium",
  },
  {
    id: "b-003",
    title: "Dropdown menu overlaps modal",
    description: "Dropdown menu z-index is higher than modal background.",
    priority: "low",
    impact: "low",
    status: "closed",
    assigneeId: "u-003",
    createdAt: "2025-06-09",
    timeSpent: 0.2,
    updates: [],
    stepsToReproduce:
      "1. Open dropdown\n2. Trigger modal\n3. Dropdown remains visible",
    environment: "Firefox on Ubuntu",
    startDate: "2025-06-09T09:00:00Z",
    endDate: "2025-06-09T15:00:00Z",
    severity: "low",
  },
  {
    id: "b-004",
    title: "API returns 500 on invalid task ID",
    description: "The /tasks/:id endpoint fails for non-existing IDs.",
    priority: "high",
    impact: "high",
    status: "in_progress",
    assigneeId: "u-004",
    createdAt: "2025-06-11",
    timeSpent: 3.2,
    updates: [],
    stepsToReproduce: "1. Hit /tasks/invalid-id\n2. Receive 500 response",
    environment: "Postman / cURL",
    startDate: "2025-06-11T10:00:00Z",
    endDate: "2025-06-14T10:00:00Z",
    severity: "critical",
  },
  {
    id: "b-005",
    title: "Text overflows on narrow screens",
    description: "Task titles overflow the card container.",
    priority: "low",
    impact: "medium",
    status: "open",
    assigneeId: "u-001",
    createdAt: "2025-06-12",
    timeSpent: 1.0,
    updates: [],
    stepsToReproduce:
      "1. Resize browser to 300px\n2. See overflow in card title",
    environment: "Chrome Dev Tools (mobile view)",
    startDate: "2025-06-12T11:00:00Z",
    endDate: "2025-06-13T11:00:00Z",
    severity: "low",
  },
  {
    id: "b-006",
    title: "Clerk user ID not saving to DB",
    description: "Sign-up flow doesn't persist user ID in database.",
    priority: "high",
    impact: "critical",
    status: "open",
    assigneeId: "u-005",
    createdAt: "2025-06-13",
    timeSpent: 2.0,
    updates: [],
    stepsToReproduce:
      "1. Register user via Clerk\n2. Check DB entry\n3. ID is null",
    environment: "Next.js 14, PostgreSQL",
    startDate: "2025-06-13T09:00:00Z",
    endDate: "2025-06-14T09:00:00Z",
    severity: "critical",
  },
  {
    id: "b-007",
    title: "Notifications not appearing on task update",
    description: "No toast shown when a task is updated.",
    priority: "medium",
    impact: "medium",
    status: "pending_approval",
    assigneeId: "u-002",
    createdAt: "2025-06-11",
    timeSpent: 0.8,
    updates: [],
    stepsToReproduce: "1. Update task\n2. No toast shown",
    environment: "All browsers",
    startDate: "2025-06-11T12:00:00Z",
    endDate: "2025-06-13T12:00:00Z",
    severity: "medium",
  },
  {
    id: "b-008",
    title: "Dark mode breaks input visibility",
    description: "Text inside inputs becomes unreadable in dark mode.",
    priority: "high",
    impact: "medium",
    status: "closed",
    assigneeId: "u-003",
    createdAt: "2025-06-12",
    timeSpent: 1.0,
    updates: [],
    stepsToReproduce:
      "1. Enable dark mode\n2. Navigate to login form\n3. Type in input field",
    environment: "Next.js 14, Chrome on Windows",
    startDate: "2025-06-12T13:00:00Z",
    endDate: "2025-06-13T13:00:00Z",
    severity: "high",
  },
  {
    id: "b-009",
    title: "Multiple form submissions on double click",
    description:
      "Submit button doesn't prevent multiple submissions on fast clicks.",
    priority: "medium",
    impact: "high",
    status: "in_progress",
    assigneeId: "u-004",
    createdAt: "2025-06-13",
    timeSpent: 1.5,
    updates: [],
    stepsToReproduce: "1. Double click submit button\n2. Observe two requests",
    environment: "Safari & Firefox latest",
    startDate: "2025-06-13T11:00:00Z",
    endDate: "2025-06-14T11:00:00Z",
    severity: "medium",
  },
  {
    id: "b-010",
    title: "Session timeout not redirecting to login",
    description: "Expired sessions silently fail without redirect.",
    priority: "high",
    impact: "high",
    status: "open",
    assigneeId: "u-005",
    createdAt: "2025-06-14",
    timeSpent: 0.7,
    updates: [],
    stepsToReproduce:
      "1. Stay idle for >30min\n2. Try an action\n3. App stays on same screen",
    environment: "Next.js app with Clerk",
    startDate: "2025-06-14T09:30:00Z",
    endDate: "2025-06-14T12:30:00Z",
    severity: "critical",
  },
  {
    id: "b-011",
    title: "Toast overlaps bottom nav on mobile",
    description: "Toast notifications appear behind bottom navigation.",
    priority: "low",
    impact: "low",
    status: "closed",
    assigneeId: "u-001",
    createdAt: "2025-06-12",
    timeSpent: 0.4,
    updates: [],
    stepsToReproduce:
      "1. Trigger toast on mobile\n2. See toast hidden by nav bar",
    environment: "React 18, Tailwind CSS",
    startDate: "2025-06-12T15:00:00Z",
    endDate: "2025-06-12T17:00:00Z",
    severity: "low",
  },
  {
    id: "b-012",
    title: "Time tracker resets on page reload",
    description: "Ongoing tracked time is lost on refresh.",
    priority: "medium",
    impact: "high",
    status: "in_progress",
    assigneeId: "u-002",
    createdAt: "2025-06-13",
    timeSpent: 2.3,
    updates: [],
    stepsToReproduce:
      "1. Start tracking time\n2. Refresh page\n3. Time resets to 0",
    environment: "Chrome/Firefox, LocalStorage enabled",
    startDate: "2025-06-13T10:00:00Z",
    endDate: "2025-06-14T10:00:00Z",
    severity: "medium",
  },
  {
    id: "b-013",
    title: "Keyboard navigation skips delete button",
    description: "Tab key doesn't focus delete buttons in task list.",
    priority: "low",
    impact: "medium",
    status: "closed",
    assigneeId: "u-003",
    createdAt: "2025-06-14",
    timeSpent: 0.6,
    updates: [],
    stepsToReproduce:
      "1. Navigate with tab\n2. Try deleting a task using keyboard only",
    environment: "All browsers, screen readers",
    startDate: "2025-06-14T08:00:00Z",
    endDate: "2025-06-15T08:00:00Z",
    severity: "low",
  },
  {
    id: "b-014",
    title: "Search results do not match filter",
    description: "Search shows incorrect results after filter is applied.",
    priority: "high",
    impact: "high",
    status: "open",
    assigneeId: "u-005",
    createdAt: "2025-06-14",
    timeSpent: 1.8,
    updates: [],
    stepsToReproduce:
      "1. Apply 'open' status filter\n2. Search a task title\n3. See closed tasks in results",
    environment: "Next.js 14, PostgreSQL",
    startDate: "2025-06-14T10:00:00Z",
    endDate: "2025-06-15T10:00:00Z",
    severity: "high",
  },
];
