import { Task } from "@/types";


export const tasks: Task[] = [
  {
    id: "t-001",
    title: "Implement login UI",
    description: "Build login page with Clerk modal",
    priority: "low",
    status: "closed",
    assigneeId: "u-001",
    startDate: "2025-06-10",
    endDate: "2025-06-14",
    updates: [],
    createdAt: "2025-06-10",
    timeSpent: 2.5,
  },
  {
    id: "t-002",
    title: "Setup Redux store",
    description: "Configure Redux Toolkit and create slices for tasks and bugs",
    priority: "high",
    status: "closed",
    assigneeId: "u-002",
    startDate: "2025-06-08",
    endDate: "2025-06-09",
    updates: [],
    createdAt: "2025-06-08",
    timeSpent: 3.0,
  },
  {
    id: "t-003",
    title: "Create dashboard layout",
    description: "Developer dashboard with task and bug sections",
    priority: "medium",
    status: "open",
    assigneeId: "u-003",
    startDate: "2025-06-12",
    endDate: "2025-06-16",
    updates: [],
    createdAt: "2025-06-12",
    timeSpent: 0,
  },
  {
    id: "t-004",
    title: "Design task card component",
    description: "Reusable card UI to display task info",
    priority: "low",
    status: "open",
    assigneeId: "u-001",
    startDate: "2025-06-13",
    endDate: "2025-06-15",
    updates: [],
    createdAt: "2025-06-13",
    timeSpent: 0,
  },
  {
    id: "t-005",
    title: "Add filtering by priority",
    description: "Allow filtering tasks by priority using dropdown",
    priority: "medium",
    status: "in_progress",
    assigneeId: "u-002",
    startDate: "2025-06-13",
    endDate: "2025-06-16",
    updates: [],
    createdAt: "2025-06-13",
    timeSpent: 1.2,
  },
  {
    id: "t-006",
    title: "Connect task CRUD to API",
    description: "Wire up frontend task forms with FastAPI endpoints",
    priority: "high",
    status: "open",
    assigneeId: "u-003",
    startDate: "2025-06-14",
    endDate: "2025-06-18",
    updates: [],
    createdAt: "2025-06-14",
    timeSpent: 0,
  },
  {
    id: "t-007",
    title: "Time tracking feature",
    description: "Track and display time spent on each task",
    priority: "low",
    status: "pending_approval",
    assigneeId: "u-004",
    startDate: "2025-06-12",
    endDate: "2025-06-17",
    updates: [],
    createdAt: "2025-06-12",
    timeSpent: 0.5,
  },
  {
    id: "t-008",
    title: "Add due date reminders",
    description: "Send reminders a day before task endDate",
    priority: "medium",
    status: "pending_approval",
    assigneeId: "u-002",
    startDate: "2025-06-11",
    endDate: "2025-06-15",
    updates: [],
    createdAt: "2025-06-11",
    timeSpent: 1.8,
  },
  {
    id: "t-009",
    title: "Mobile responsiveness",
    description: "Ensure dashboard works well on all screen sizes",
    priority: "medium",
    status: "in_progress",
    assigneeId: "u-001",
    startDate: "2025-06-13",
    endDate: "2025-06-17",
    updates: [],
    createdAt: "2025-06-13",
    timeSpent: 1.0,
  },
  {
    id: "t-010",
    title: "Optimize Redux performance",
    description: "Memoize selectors and split slices for scalability",
    priority: "high",
    status: "open",
    assigneeId: "u-005",
    startDate: "2025-06-14",
    endDate: "2025-06-19",
    updates: [],
    createdAt: "2025-06-14",
    timeSpent: 0,
  },
];
